// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvw-uakbrO3iM0NWDbBswPr8uow4Fu37A',
    appId: '1:617929026568:android:2f9fff898600d9b19eb5bd',
    messagingSenderId: '617929026568',
    projectId: 'awari-3fc51',
    storageBucket: 'awari-3fc51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbEsbRsxCTkZkODUdOFxDgZ_A5RVTBlgU',
    appId: '1:617929026568:ios:20b27df183bc78289eb5bd',
    messagingSenderId: '617929026568',
    projectId: 'awari-3fc51',
    storageBucket: 'awari-3fc51.appspot.com',
    androidClientId: '617929026568-h87ub0podcge9t7b2m4sca8kvrd2h95t.apps.googleusercontent.com',
    iosClientId: '617929026568-pra3jtht23gmvt4pldltmup92gp5g4l2.apps.googleusercontent.com',
    iosBundleId: 'com.example.awarisupport',
  );
}
